services:
  - type: web
    name: quant-enthusiasts-risk-engine
    env: python
    region: oregon
    plan: free
    buildCommand: bash start.sh
    startCommand: cd python_api && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18
      - key: RENDER
        value: true
      - key: PORT
        value: 10000